### ISSUE TITLE
Problem with my system?

### ISSUE THREAD

**Issue by miloskroulik** [Boaterfly/ansible-role-simp_le#4] opened 2016-03-13 14:36 UTC
First, thanks a lot for the role. I'm trying to use it, but I experienced an error at `Create certificates` step:

`fatal: [37.205.11.220]: FAILED! => {"changed": true, "cmd": ["/home/root/.cache/ansible-simp_le/generate-certs", "/home/root/.cache/ansible-simp_le/conf.json"], "delta": "0:00:00.027201", "end": "2016-03-13 14:27:54.053156", "failed": true, "rc": 1, "start": "2016-03-13 14:27:54.025955", "stderr": "Traceback (most recent call last):\n  File \"/home/root/.cache/ansible-simp_le/generate-certs\", line 77, in <module>\n    main(sys.argv)\n  File \"/home/root/.cache/ansible-simp_le/generate-certs\", line 68, in main\n    ret = subprocess.call(cmd, cwd=vhost[\"output\"])\n  File \"/usr/lib/python2.7/subprocess.py\", line 522, in call\n    return Popen(*popenargs, **kwargs).wait()\n  File \"/usr/lib/python2.7/subprocess.py\", line 710, in __init__\n    errread, errwrite)\n  File \"/usr/lib/python2.7/subprocess.py\", line 1327, in _execute_child\n    raise child_exception\nOSError: [Errno 2] No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}`

I'm using Ubuntu 14.04 and don't know, what file or directory could be missing.

**Comment by L-P** [comment] 2016-03-13 18:11
I have yet to test if this is the cause of your problem but you are not
supposed to run this role as root/sudo.

Can you give me the contents of `/home/root/.cache/ansible-simp_le/conf.json`?

**Comment by miloskroulik** [comment] 2016-03-13 18:16
`{"dest": "/home/root/.cache/ansible-simp_le/simp_le", "vhosts": [{"domains": ["www.shaarli.milhaus.cz", "shaarli.milhaus.cz"], "output": "/var/certs/shaarli_milhaus_cz", "root": "/var/www/shaarli/.well-known/acme-challenge"}], "email": "<my_email>"}`

All the directories do exist. Also, I'm using that VPS as root through SSH, is that a problem?

**Comment by L-P** [comment] 2016-03-13 19:05
I use this role on multiple VPS running Ubuntu 14.04 and it works fine, but it
is designed to run as an unprivileged user.

Hence the hackish thing I did in `defaults/main.yml`, I use `/home/<user>` as
the remote user home directory so the cache is written in `/home∕root/.cache`
instead of `/root/.cache`.

You'll want to set the following variable if you plan to keep using root:

``` yaml
simp_le_cache: "/root/.cache/ansible-simp_le"               
```

I successfully ran the role as root on Ubuntu 14.04.

Does `/home/root/.cache/ansible-simp_le/simp_le/venv/bin/simp_le` exist?

**Comment by miloskroulik** [comment] 2016-03-13 19:19
Yes, it exists. I set the variable you mentioned, but the problem remains.

**Comment by L-P** [comment] 2016-03-14 09:27
Edit `~/.cache/ansible-simp_le/generate-certs` and print `cmd` and
`vhost["output"]` before [L68](https://github.com/Boaterfly/ansible-role-simp_le/blob/060625f46326064c927c10cb07fa1a5644c5702a/files/generate-certs#L68).  
See if both paths are correct and exist.

**Comment by ghostwords** [comment] 2016-03-14 13:39
I believe the issue is in the generate-certs script caused by a leading slash in the second argument to os.path.join. Proposed fix:

``` diff
43c43
<     command = [os.path.join(conf["dest"], "/venv/bin/simp_le")]
---
>     command = [os.path.join(conf["dest"], "venv", "bin", "simp_le")]
```

**Comment by L-P** [comment] 2016-03-14 16:45
Confirmed. ~~I wonder why it worked for me.~~ I tested with v1.1.0, the
bug was introduced in 060625f4, first thing I should have asked was the
version you were using.

This is fixed in master, can you try again @miloskroulik ?

**Comment by miloskroulik** [comment] 2016-03-14 19:15
Yes, I can confirm that it works afterwards. Thanks a lot @ghostwords and @L-P

**Closed as completed** 2016-03-15 08:35 UTC
